import "./globals.css";
import localfont from "next/font/local";
import { Golos_Text } from "next/font/google";
import { Unbounded } from "next/font/google";

const druk = localfont({
  src: [
    {
      path: '../../public/fonts/DrukCyr-Medium.otf',
      weight: '500',
      style: 'medium'
    },
    {
      path: '../../public/fonts/DrukCyr-Bold.ttf',
      weight: '700',
      style: 'bold'
    },
    {
      path: '../../public/fonts/DrukCyr-Heavy.ttf',
      weight: '800',
      style: 'extrabold'
    }
  ],
  variable: '--font-druk'
});

const golos = Golos_Text ({
  subsets: ['cyrillic'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-golos'
});

const unbounded = Unbounded({
  subsets: ['cyrillic'],
  display: 'swap',
  weight: ['400', '500', '600','700'],
  variable: '--font-unbounded'
})

export const metadata = {
  title: "PiterGSM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${druk.variable} ${golos.variable} ${unbounded.variable}`}>{children}</body>
    </html>
  );
}
